# Generated by Django 4.1.6 on 2023-02-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author', verbose_name='book author'),
        ),
    ]
